create table "ftuser"
(
    id       integer generated by default as identity
        constraint user_pk
        primary key,
    email    varchar(64)  not null,
    password varchar(256) not null
);

alter table "ftuser"
    owner to postgres;

create table "ftsession"
(
    id       integer generated by default as identity
        constraint session_pk
        primary key,
    user_id         integer                             not null
        constraint session_user_id_fk
            references "ftuser",
    token varchar(256) not null,
    created_at      timestamp default CURRENT_TIMESTAMP not null,
    expire_at      timestamp
);

alter table "ftsession"
    owner to postgres;

create table channel
(
    id              integer generated by default as identity
        constraint channel_pk
        primary key,
    user_id         integer                             not null
        constraint channel_user_id_fk
            references "ftuser",
    username        varchar(64)                         not null
        constraint unique_username
            unique,
    description     varchar(256)                        not null,
    created_at      timestamp default CURRENT_TIMESTAMP not null,
    updated_at      timestamp,
    profile_picture bytea
);

alter table channel
    owner to postgres;

create table playlist
(
    id         integer generated by default as identity
        constraint playlist_pk
        primary key,
    channel_id    integer                             not null
        constraint playlist_channel_id_fk
            references "channel",
    name       varchar(64)                         not null,
    created_at timestamp default CURRENT_TIMESTAMP not null,
    updated_at timestamp
);

alter table playlist
    owner to postgres;

create table video
(
    id          integer generated by default as identity
        constraint video_pk
        primary key,
    channel_id  integer                             not null
        constraint video_channel_id_fk
            references channel,
    title       varchar(64)                         not null,
    description varchar(256)                        not null,
    thumbnail   bytea,
    duration    double precision,
    is_public   boolean,
    created_at  timestamp default CURRENT_TIMESTAMP not null,
    updated_at  timestamp
);

alter table video
    owner to postgres;

create table playlist_video
(
    playlist_id integer                             not null
        references playlist,
    video_id    integer                             not null
        references video,
    added_at    timestamp default CURRENT_TIMESTAMP not null,
    primary key (playlist_id, video_id)
);

alter table playlist_video
    owner to postgres;

create table hashtag
(
    id   integer generated by default as identity
        constraint hashtag_pk
        primary key,
    name varchar(32) not null
        constraint unique_name
            unique
);

alter table hashtag
    owner to postgres;

create table video_hashtag
(
    hashtag_id integer not null
        references hashtag,
    video_id   integer not null
        references video,
    primary key (hashtag_id, video_id)
);

alter table video_hashtag
    owner to postgres;

create table subscription
(
    subscriber_id integer not null
        references channel,
    channel_id    integer not null
        references channel,
    primary key (subscriber_id, channel_id)
);

alter table subscription
    owner to postgres;

create table history
(
    video_id   integer                             not null
        references video,
    channel_id integer                             not null
        references channel,
    seen_at    timestamp default CURRENT_TIMESTAMP not null,
    primary key (video_id, channel_id)
);

alter table history
    owner to postgres;

create table reaction
(
    id         integer generated by default as identity
        constraint reaction_pk
        primary key,
    channel_id integer                             not null
        constraint reaction_channel_id_fk
            references channel,
    video_id   integer                             not null
        constraint reaction_video_id_fk
            references video,
    type       integer,
    created_at timestamp default CURRENT_TIMESTAMP not null
);

alter table reaction
    owner to postgres;

create table comment
(
    id         integer generated by default as identity
        constraint comment_pk
        primary key,
    channel_id integer                             not null
        constraint reaction_channel_id_fk
            references channel,
    video_id   integer                             not null
        constraint reaction_video_id_fk
            references video,
    content    varchar(256),
    created_at timestamp default CURRENT_TIMESTAMP not null
);

alter table comment
    owner to postgres;

