services:
  postgres:
    image: postgres:16-alpine
    networks:
      shared_net:
        ipv4_address: 172.25.0.2
    ports:
      - 5432:5432
    volumes:
      - pg_volume:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5

  back:
    build:
      context: ./3PROJ-Back
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      shared_net:
        ipv4_address: 172.25.0.3
    environment:
      - PG_JDBC=postgres
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/q/health/live"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 15s

volumes:
  pg_volume:

networks:
  shared_net:
    ipam:
      driver: default
      config:
        - subnet: 172.25.0.0/24
          gateway: 172.25.0.1

